version: 0.2
phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
artifacts:
  files:
    - '**/*'
  name: BuildArtifact
cache:
  paths:
    - node_modules/